description: null
enabled: true
fileNameFormat: 'order-invoice-{number}'
handle: invoice
isDefault: true
language: orderLanguage
name: Invoice
sortOrder: 9999
store: 084e99dd-eb3e-4322-8616-8a04eda795ae
templatePath: _special/pdfs/invoice
