bcc: null
cc: null
enabled: false
language: orderLanguage
name: 'Order Shipped'
plainTextTemplatePath: null
recipientType: customer
replyTo: null
store: 084e99dd-eb3e-4322-8616-8a04eda795ae
subject: '{{order.shortNumber}} Shipped!'
templatePath: _special/emails/shipped
to: null
