field: a42d1365-22cd-445e-9e10-43dc721bddbe # Button
fieldLayouts:
  4e683645-3a9f-4fa8-96a1-8de2cc285fe0:
    tabs:
      -
        elements:
          -
            fieldUid: 6d832652-3b7e-417c-8a96-14965cdfd744 # Button - Button - Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb77724f-26e2-4302-9975-70c6edbbf5b4
            warning: null
            width: 100
          -
            fieldUid: 3815aa30-9bf2-4a2b-8d16-00fd08c68e86 # Button - Button - Aria Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63f8229c-6f4b-4d48-94e8-57f84447bb36
            warning: null
            width: 100
          -
            fieldUid: ee205f0d-9016-48b3-8c84-df68b08003cd # Button - Button - Entry Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77e5293e-76f5-4e33-94ca-934a286ba769
            warning: null
            width: 100
          -
            fieldUid: 7f531774-b9c9-4fde-8708-762f09ef7191 # Button - Button - Category Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2ad506c-2942-4f40-84e1-26c2aab9aafe
            warning: null
            width: 100
          -
            fieldUid: 6443fbe4-a797-4f2a-8b81-c76619128990 # Button - Button - Button URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec3ceb16-1d3c-46dd-80fb-054c895b2f70
            warning: null
            width: 100
        name: Content
        uid: 4242747f-13aa-4ca5-a783-a8d32fe97610
fields:
  6d832652-3b7e-417c-8a96-14965cdfd744: # Button - Button - Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7f531774-b9c9-4fde-8708-762f09ef7191: # Button - Button - Category Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: categoryLink
    instructions: 'Select a category to link to (leave blank if using the button URL).'
    name: 'Category Link'
    searchable: false
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      branchLimit: 1
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: false
      source: 'group:aa40a16f-55f6-4e2c-818c-5e1f6a3a5b57' # Bike Types
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  3815aa30-9bf2-4a2b-8d16-00fd08c68e86: # Button - Button - Aria Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: ariaLabel
    instructions: null
    name: 'Aria Label'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6443fbe4-a797-4f2a-8b81-c76619128990: # Button - Button - Button URL
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonUrl
    instructions: 'Use this field if you require linking to a custom URL that is not an entry or category.'
    name: 'Button URL'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ee205f0d-9016-48b3-8c84-df68b08003cd: # Button - Button - Entry Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entryLink
    instructions: 'Select and entry to link to (leave this blank when linking to a category or using the button URL)'
    name: 'Entry Link'
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      selectionLabel: null
      showSiteMenu: false
      source: null
      sources:
        - 'section:21dd60d6-92a7-4e82-8884-7dbe57d73c6c' # Account
        - 'section:506e9a86-f8ca-4f35-bffc-21da95813979' # Articles
        - 'section:f6e39d3c-bc6d-4fac-b921-c655cde09804'
        - 'section:2fad1c7c-c4f2-4fdf-9154-8c88bcc18db5' # Landing Pages
        - singles
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: button
name: Button
sortOrder: 1
