field: bd167f4d-e985-4aec-b6e4-9ba85fbe69f9 # Content Blocks
fieldLayouts:
  3474d9f8-95a1-4792-b81f-3c0cfd36d4ce:
    tabs:
      -
        elements:
          -
            fieldUid: 4618ebbc-ed9f-4632-8648-dbbfafc12ce5 # Content Blocks - Form - Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 285b26c6-8b36-473a-9e21-6c40e17b14af
            warning: null
            width: 100
          -
            fieldUid: 520350fa-6eaf-4bc0-9568-687055d5b462 # Content Blocks - Form - Form
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50bdbb96-cd19-4398-9e33-5e08f9142eb9
            warning: null
            width: 100
        name: Content
        uid: 4616725f-bb07-4e36-bd8a-1ee016952735
fields:
  4618ebbc-ed9f-4632-8648-dbbfafc12ce5: # Content Blocks - Form - Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Enter an optional heading to be displayed above the form.'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  520350fa-6eaf-4bc0-9568-687055d5b462: # Content Blocks - Form - Form
    columnSuffix: null
    contentColumnType: integer
    fieldGroup: null
    handle: form
    instructions: 'Choose the form youâ€™d like to display on this page.'
    name: Form
    searchable: false
    translationKeyFormat: null
    translationMethod: none
    type: Solspace\Freeform\FieldTypes\FormFieldType
handle: form
name: Form
sortOrder: 4
