field: bd167f4d-e985-4aec-b6e4-9ba85fbe69f9 # Content Blocks
fieldLayouts:
  a4d40528-744c-4343-940a-f76056228c2d:
    tabs:
      -
        elements:
          -
            fieldUid: 4ddf421a-c279-4733-9b0c-2df498c98ec8 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4ddf421a-c279-4733-9b0c-2df498c98ec8: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'Choose a reasonably-large image to be displayed at full width. (Will automatically be cropped to various sizes.)'
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:994a420b-cb3e-4813-be6a-dd7ac7f55c6b' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:994a420b-cb3e-4813-be6a-dd7ac7f55c6b' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: fullWidthImage
name: 'Full Width Image'
sortOrder: 2
