field: b9cb6112-ebae-420b-bae9-a54c387419f6 # Footer Nav
fieldLayouts:
  a07d3103-a401-4270-a15f-172faf15aade:
    tabs:
      -
        elements:
          -
            fieldUid: a004cfa0-a7f8-419b-8343-d6670a0a52e8 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0e97bea-8697-4afa-9270-2d73b0f0c799
            warning: null
            width: 100
          -
            fieldUid: 18ab3594-a62d-4903-9c6c-b791d64fd4ad # Pages
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bf65e99-ab15-4e4f-95a5-525f6ac35b70
            warning: null
            width: 100
        name: Content
        uid: 46a8ecc6-3e5e-4a43-8b55-055b059ff0af
fields:
  18ab3594-a62d-4903-9c6c-b791d64fd4ad: # Pages
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: pages
    instructions: 'Select the pages that should be displayed in this column.'
    name: Pages
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionLabel: 'Add a page'
      showSiteMenu: true
      source: null
      sources:
        - 'section:2fad1c7c-c4f2-4fdf-9154-8c88bcc18db5' # Landing Pages
        - singles
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  a004cfa0-a7f8-419b-8343-d6670a0a52e8: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Enter an optional column heading.'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: pages
name: Pages
sortOrder: 1
