field: bd167f4d-e985-4aec-b6e4-9ba85fbe69f9 # Content Blocks
fieldLayouts:
  bd5cdfbd-9eb4-42c1-a500-37732ab3f1c7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d6666f58-4d11-4bd3-b5bd-bc92b52a538c # Products
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e03db92-e525-4e6f-890e-bd74e540862b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b89de1a7-7320-4ddd-8c5c-6bce35abf395
        userCondition: null
fields:
  d6666f58-4d11-4bd3-b5bd-bc92b52a538c: # Products
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: products
    instructions: 'Select up to three products to promote.'
    name: Products
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 3
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\commerce\fields\Products
handle: products
name: Products
sortOrder: 3
