field: b9cb6112-ebae-420b-bae9-a54c387419f6 # Footer Nav
fieldLayouts:
  007ad558-50e4-45ef-a6bf-44c60060e91e:
    tabs:
      -
        elements:
          -
            fieldUid: d5599be5-4ce7-4f5f-997b-843257caca75 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7eabce9-a70c-4ec2-9ce4-724e9e9b32a5
            warning: null
            width: 100
          -
            fieldUid: e1227ec6-29cc-4c76-8ef1-a091a264b805 # Product Categories
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b939901-31b3-44ff-ae3c-4e6ad5b0490b
            warning: null
            width: 100
        name: Content
        uid: bea798e1-1f9b-484e-85ea-64b2eb9c78b9
fields:
  d5599be5-4ce7-4f5f-997b-843257caca75: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Enter an optional heading for this column.'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e1227ec6-29cc-4c76-8ef1-a091a264b805: # Product Categories
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: productCategories
    instructions: 'Select product categories that should be displayed in this column.'
    name: 'Product Categories'
    searchable: false
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      source: 'group:aa40a16f-55f6-4e2c-818c-5e1f6a3a5b57' # Bike Types
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
handle: productCategories
name: 'Product Categories'
sortOrder: 2
