fieldLayouts:
  97801d55-b621-4a1a-bcd1-c92fbb24b7c4:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a3fc9677-0954-485a-943c-63a91096ac56
            warning: null
            width: 100
        name: Content
        uid: add6cb0c-11f6-4885-8e0b-efb3e0c70a6c
      -
        elements:
          -
            fieldUid: e7ec0fe3-e0bc-474d-837d-3159984e36f3 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90c89520-4161-4ffe-9451-547d6610cdf2
            warning: null
            width: 100
        name: SEO
        uid: 12c80604-be6e-4fb1-bf4b-b6aed0671b29
handle: articlesLanding
hasTitleField: true
name: 'Articles Landing'
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
