fieldLayouts:
  dbde3903-52ad-440e-b0a3-d8947421b704:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0619a776-852d-4a6b-82cd-f10d52febd27
            warning: null
            width: 100
          -
            fieldUid: 5572edd6-3495-4a53-8f09-68bb6c53d79a # Main Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7440299f-def0-4655-8615-2a81933fcbac
            warning: null
            width: 100
          -
            fieldUid: bd167f4d-e985-4aec-b6e4-9ba85fbe69f9 # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb9868ff-050c-4fce-97e2-bb4c7b9c295e
            warning: null
            width: 100
        name: Content
        uid: 53718f1d-d11d-45c1-9e9f-0d7395ffb693
      -
        elements:
          -
            fieldUid: e7ec0fe3-e0bc-474d-837d-3159984e36f3 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4f37c46-07b1-442c-8a1a-c77132e00b6e
            warning: null
            width: 100
        name: SEO
        uid: ffb8e503-7e9b-4d83-a813-7bac89c8da3e
handle: articles
hasTitleField: true
name: Articles
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
