fieldLayouts:
  2ac896d4-c65e-4d74-b4ec-f26cf1d3053d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0aa64e89-178a-4fee-86c7-5fb4329296b0
            warning: null
            width: 100
          -
            fieldUid: 5572edd6-3495-4a53-8f09-68bb6c53d79a # Main Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5373666-f3f5-4436-9c11-3b5cfae14f59
            warning: null
            width: 100
        name: Content
        uid: 605c8167-2548-44a9-a6b1-750297eded92
      -
        elements:
          -
            fieldUid: e7ec0fe3-e0bc-474d-837d-3159984e36f3 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cca88b68-e434-4c42-a75a-436d499d61dc
            warning: null
            width: 100
        name: SEO
        uid: 4a9da9d8-4123-4370-9f7e-48fa6da33c4d
handle: bikesLanding
hasTitleField: false
name: Bikes
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
