color: null
fieldLayouts:
  13c1626f-d23d-4ed1-8205-b49108b53edc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2e8e706d-cbc4-4433-a3b1-2a7a4be18ee2 # Content Blocks - Body - Body
            handle: body
            includeInCards: true
            instructions: null
            label: Body
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72074312-5efa-4c45-a3e8-f0d4b104b072
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 03f1355e-67b8-457a-b8e9-20cbc34af8c4 # Content Blocks - Body - Intro
            handle: null
            includeInCards: false
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 179194cc-fda8-4a3f-a004-56134bc991df
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 38e8252e-7338-4d4e-92c8-ab9b7073b3e5
        userCondition: null
handle: body
hasTitleField: false
icon: null
name: Body
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
