fieldLayouts:
  d6bab467-3ac2-4092-9bf6-30c86263d0c5:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b820b4fe-5c1e-4958-8bcd-ccb1a11e5202
            warning: null
            width: 100
          -
            fieldUid: 708be4d3-74b6-4389-a32f-aebc64f33b0d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29df2851-4c81-46b0-b08d-13c150cd835c
            warning: null
            width: 100
          -
            fieldUid: edcd5813-3fcd-4824-9a2e-e1f6d92c7fdf # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68194d2f-73c2-4023-97d0-aeaea812a2fa
            warning: null
            width: 100
          -
            fieldUid: 86ec2b26-5d53-4798-8fb0-927890e52039 # Body
            instructions: null
            label: 'No items content'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8e52b15-ffe5-4144-aed0-f06b6f617ddb
            warning: null
            width: 100
        name: Content
        uid: 56485d23-f4b1-452c-b634-556650094149
      -
        elements:
          -
            fieldUid: e7ec0fe3-e0bc-474d-837d-3159984e36f3 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ad389b5-fde0-4b7e-9f15-4632eae7ba20
            warning: null
            width: 100
        name: SEO
        uid: f14e7211-14e6-4b24-b9e4-c53dc1ec4055
handle: cart
hasTitleField: true
name: Cart
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
