fieldLayouts:
  f8853b83-c030-4ebe-896c-e344ed6abef0:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b5b2d67d-0707-4d8a-8ddb-f81bdf33cdfb
            warning: null
            width: 100
          -
            fieldUid: 708be4d3-74b6-4389-a32f-aebc64f33b0d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36dd0791-f7b9-4df7-a18e-56ce06805936
            warning: null
            width: 100
        name: Content
        uid: a090d9e3-a80b-4295-a853-f9c5b7106299
      -
        elements:
          -
            fieldUid: e7ec0fe3-e0bc-474d-837d-3159984e36f3 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83e47497-72cc-42d8-82b8-6028948b9381
            warning: null
            width: 100
        name: SEO
        uid: 6eb70a19-3ed8-42c1-b74c-4180addcb873
handle: checkoutSummary
hasTitleField: true
name: 'Checkout: Summary'
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
