fieldLayouts:
  2c848203-93d2-43d6-ae56-ba3061b45736:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6198da72-c3cb-4a18-b3d3-aeb299320ee6
            warning: null
            width: 100
          -
            fieldUid: 708be4d3-74b6-4389-a32f-aebc64f33b0d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77a1b8f6-1c5b-4182-b9f6-ac9554c91ba8
            warning: null
            width: 100
        name: Content
        uid: 27a5eac8-1d29-4aae-9bd2-2ed55a3f0ce8
      -
        elements:
          -
            fieldUid: e7ec0fe3-e0bc-474d-837d-3159984e36f3 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6c99fec-0ecd-4d05-af34-b7ac811be65e
            warning: null
            width: 100
        name: SEO
        uid: c4e7f07d-5213-4f26-a4e4-87b4bc1c2684
handle: checkoutAddress
hasTitleField: true
name: 'Checkout: Address'
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
