fieldLayouts:
  26ba6c2d-9984-4cee-827b-6a35223f1d16:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 638615eb-4179-4f4a-b0ff-2d1fbb302a16
            warning: null
            width: 100
          -
            fieldUid: edcd5813-3fcd-4824-9a2e-e1f6d92c7fdf # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 745a07c8-7851-42de-b704-ba5ce7e94f99
            warning: null
            width: 100
        name: Content
        uid: cb403120-3956-4c6f-8370-e40eb2edd949
      -
        elements:
          -
            fieldUid: e7ec0fe3-e0bc-474d-837d-3159984e36f3 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21f8dc80-7de5-4a5b-bcce-792590fa3138
            warning: null
            width: 100
        name: SEO
        uid: 5e441239-d1dd-49ea-9c70-fed10f93686e
handle: contact
hasTitleField: false
name: Contact
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
