fieldLayouts:
  c283d1c6-ce00-418b-930b-2d241302e920:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9e394782-cd27-4158-a253-f4b764a690ec
            warning: null
            width: 100
          -
            fieldUid: 708be4d3-74b6-4389-a32f-aebc64f33b0d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed285f15-e6c8-4801-97fe-1b75115fd6bb
            warning: null
            width: 100
          -
            fieldUid: 5572edd6-3495-4a53-8f09-68bb6c53d79a # Main Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21168102-1a7f-4bc5-96be-0eb1d111fc69
            warning: null
            width: 100
          -
            fieldUid: a42d1365-22cd-445e-9e10-43dc721bddbe # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f9e8c9d-b725-41c0-8145-bead75143e12
            warning: null
            width: 100
        name: Content
        uid: 6bbea475-b016-4b0a-a148-216038ee25d6
      -
        elements:
          -
            fieldUid: e7ec0fe3-e0bc-474d-837d-3159984e36f3 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ea7ea2f-87a6-492f-b39d-1b561eb56079
            warning: null
            width: 100
        name: SEO
        uid: be74158e-e925-459b-bca6-74d8044e024e
handle: homepage
hasTitleField: false
name: Homepage
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
