fieldLayouts:
  2001d55a-3bd3-4600-8ee8-e3ef1b6899de:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 45854963-804e-4615-84ac-372e0fc13ac0
            warning: null
            width: 100
          -
            fieldUid: edcd5813-3fcd-4824-9a2e-e1f6d92c7fdf # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 187b8eeb-3203-46ca-90c8-79880ab60cf8
            warning: null
            width: 100
        name: Content
        uid: 91783058-8e77-4cd5-8588-12205a3978d3
      -
        elements:
          -
            fieldUid: e7ec0fe3-e0bc-474d-837d-3159984e36f3 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9b63bff-525f-4656-81bf-c828e82bc630
            warning: null
            width: 100
        name: SEO
        uid: c8ffd793-e370-44eb-855b-f56a4ee83426
handle: orders
hasTitleField: true
name: Orders
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
