fieldLayouts:
  09f50636-036b-45fe-b573-04b734738d40:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3aa0efcb-c482-4a3b-88f3-95567824b34a
            warning: null
            width: 100
          -
            fieldUid: bd167f4d-e985-4aec-b6e4-9ba85fbe69f9 # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 662ec813-4c9b-43d0-b472-d9bb81fd69ee
            warning: null
            width: 100
        name: Content
        uid: 9bd126b4-4480-4379-a7ab-db9c4dce3efe
      -
        elements:
          -
            fieldUid: e7ec0fe3-e0bc-474d-837d-3159984e36f3 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af863ed6-0bfd-41e3-a4b6-5684dfd57c1a
            warning: null
            width: 100
        name: SEO
        uid: 33339ebd-d9b5-42e3-80e5-3d897dfc0328
handle: page
hasTitleField: true
name: Page
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
