fieldLayouts:
  2caa0b26-e0eb-49f6-8457-6f905d542b19:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 19859cd2-7c19-479f-a135-7334fbb0e6e9
            warning: null
            width: 100
          -
            fieldUid: 708be4d3-74b6-4389-a32f-aebc64f33b0d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4544c2d1-4b95-44e3-9faa-1983c0bf35bd
            warning: null
            width: 100
          -
            fieldUid: 86ec2b26-5d53-4798-8fb0-927890e52039 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71667137-b105-487f-92c8-290675f42566
            warning: null
            width: 100
        name: Content
        uid: 3d9b8344-a3d5-4e98-9d52-4df88939c700
handle: pdfs
hasTitleField: true
name: PDFs
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
