fieldLayouts:
  0bc1ed2c-d164-4ede-9587-a3167296f22b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: 'Plan Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 144eafb4-8a07-46d0-a4b2-e85237275206 # Plan Features
            instructions: 'Describe plan features, each having its own line.'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: plans
hasTitleField: true
name: Plans
section: 97a0491d-814e-4172-811d-51096a86e67d # Plans
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
