fieldLayouts:
  26ed06a3-4c9a-4566-be88-6ff2aa950ddf:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ac528b97-bc6c-4788-89df-f4b8128858f6
            warning: null
            width: 100
          -
            fieldUid: d3fad61c-dfb9-4da2-bb75-6d2910c3c4ca # Plain Text 1
            instructions: null
            label: 'No Results Heading'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc95fd89-6baf-428d-a59e-afb65f5713e7
            warning: null
            width: 100
          -
            fieldUid: e60fd5c1-9f1b-496d-8369-a9daafcc185d # Plain Text 2
            instructions: null
            label: 'No Results Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c132665-0abb-417e-88c2-45d6a366d11c
            warning: null
            width: 100
        name: Content
        uid: ee6e3e33-0326-420c-8252-21415a28004e
      -
        elements:
          -
            fieldUid: e7ec0fe3-e0bc-474d-837d-3159984e36f3 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 167c1c73-e360-4799-9412-b3b4b10462e1
            warning: null
            width: 100
        name: SEO
        uid: 0fba52fd-6b69-4938-92de-d12749b62c80
handle: search
hasTitleField: false
name: Search
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
