fieldLayouts:
  6d983617-98cb-4b8d-a296-b42968ecb161:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9eafb5b0-a301-44ba-8014-39bd1c65a3ef
            warning: null
            width: 100
          -
            fieldUid: edcd5813-3fcd-4824-9a2e-e1f6d92c7fdf # Subheading
            instructions: 'Used on the account dashboard page'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c116617f-44f0-46fe-b643-b5cfd261a5d0
            warning: null
            width: 100
          -
            fieldUid: d3fad61c-dfb9-4da2-bb75-6d2910c3c4ca # Plain Text 1
            instructions: null
            label: 'New Password Help Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6363eaed-ad1c-4037-ac2d-e4b31175ca83
            warning: null
            width: 100
          -
            fieldUid: e60fd5c1-9f1b-496d-8369-a9daafcc185d # Plain Text 2
            instructions: null
            label: 'Current Password Help Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e69d2ee-3672-4406-b0ac-f070ae8792c1
            warning: null
            width: 100
        name: Content
        uid: a2de9c41-2a6e-42cc-af3b-f652fa04c9b4
      -
        elements:
          -
            fieldUid: e7ec0fe3-e0bc-474d-837d-3159984e36f3 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62ec070e-632f-485e-863b-8c900623006a
            warning: null
            width: 100
        name: SEO
        uid: 3f14c402-0dfe-41f1-bcca-d69d1050cab4
handle: settings
hasTitleField: true
name: Settings
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
