defaultPlacement: end
fieldLayouts:
  21f5f824-8dec-4655-aea5-cdf2a90708fc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 262b8c65-c9fd-4c0e-a772-cccd60e99079
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e9eeb095-1668-49fe-99a2-36721c1bdbec # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef07f79f-f046-49bc-a76b-3eedfa10f021
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5572edd6-3495-4a53-8f09-68bb6c53d79a # Main Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0bb8a18-3e20-4a58-af64-b090a09aea7a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 659072b4-bec9-4e00-84d8-ae0730a8e1c7
        userCondition: null
handle: bikeTypes
name: 'Bike Types'
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    hasUrls: true
    template: _views/categories/bikes
    uriFormat: 'bikes/{slug}'
structure:
  maxLevels: 1
  uid: 9b2d9e9d-d4b8-4c6c-9954-d7680a953e52
