columnSuffix: zhgorwis
contentColumnType: text
handle: businessAddress
instructions: 'Enter the shopâ€™s physical street address.'
name: 'Business Address'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 3
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
