columnSuffix: null
contentColumnType: string(7)
fieldGroup: 6aa1ad27-db4b-4af9-8658-d93eff3d4512 # Common
handle: color
instructions: null
name: Color
searchable: false
settings:
  defaultColor: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
