columnSuffix: null
contentColumnType: string(7)
handle: color
instructions: null
name: Color
searchable: false
settings:
  defaultColor: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
