columnSuffix: null
contentColumnType: string
fieldGroup: 6aa1ad27-db4b-4af9-8658-d93eff3d4512 # Common
handle: contentBlocks
instructions: 'Use the available block types to compose the pageâ€™s main content.'
name: 'Content Blocks'
searchable: true
settings:
  contentTable: '{{%matrixcontent_contentblocks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
