contentColumnType: string
fieldGroup: 6aa1ad27-db4b-4af9-8658-d93eff3d4512
handle: equipmentType
instructions: ''
name: 'Equipment Type'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: '1'
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'group:dcef5c5f-2446-44fa-8898-1bc3daa2d2fd'
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
