columnSuffix: null
contentColumnType: text
handle: seo
instructions: null
name: SEO
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoTitle
    - seoDescription
    - seoImage
  generalTabEnabled: '1'
  sitemapTabEnabled: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
