columnSuffix: null
contentColumnType: boolean
fieldGroup: d52553ad-dd63-4dfd-8740-d53484afbcb3 # Product
handle: showForm
instructions: null
name: 'Show Form'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
