columnSuffix: null
contentColumnType: string
handle: stars
instructions: null
name: Stars
searchable: false
settings:
  maxStars: '5'
translationKeyFormat: null
translationMethod: none
type: oberon\starfield\fields\StarField
