dateModified: 1626920412
email:
  fromEmail: support@craftcms.com
  fromName: 'Spoke & Chain'
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: ''
    host: $SMTP_HOST
    password: ''
    port: $SMTP_PORT
    timeout: '10'
    useAuthentication: ''
    username: ''
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    0dbacfe0-78ef-48ff-95a3-b7eb4dc8be86: Emails # Emails
    0f590e76-b015-4dad-b3b6-4bc6e721c244: 'Order Received' # Order Received
    0f952e73-17b8-408c-9c37-3f07a5d16a92: 'Error Pages' # Error Pages
    1e81b434-e226-440b-9bcf-efb22342a5d0: Summary # Summary
    2af1095c-7195-4f2b-ad59-d4e36ee17dd9: Services # Services
    2e8e706d-cbc4-4433-a3b1-2a7a4be18ee2: Body # Body
    2fad1c7c-c4f2-4fdf-9154-8c88bcc18db5: Pages # Pages
    03b7bc53-c8e9-48e4-8f45-da16de73909b: Material # Material
    3db0de34-4e51-40f0-a195-e3ab0a071dcf: 'Product Categories' # Product Categories
    03f1355e-67b8-457a-b8e9-20cbc34af8c4: Intro # Intro
    4b6d893d-380e-4fbc-970b-ed925fba9aaf: 'Spoke & Chain' # Spoke & Chain
    4ddf421a-c279-4733-9b0c-2df498c98ec8: Image # Image
    5a97754b-a6d0-41f2-ba98-cf145d689df1: Colors # Colors
    5f3f9d21-e4a4-40d6-b80f-a92d99e02926: 'Show Form' # Show Form
    6aa1ad27-db4b-4af9-8658-d93eff3d4512: Common # Common
    6d832652-3b7e-417c-8a96-14965cdfd744: Label # Label
    06e900c5-0757-485f-bda2-2875772bbe25: Colors # Colors
    7bdf6844-d551-446c-97b6-12a24f5348e8: Checkout # Checkout
    7f531774-b9c9-4fde-8708-762f09ef7191: 'Category Link' # Category Link
    9b4d8a8b-c63e-4039-a35d-4ab24561f00b: Pages # Pages
    9b9e7f64-d3ac-4cd8-9ac6-2dad92ba68f1: Contact # Contact
    17eacd1a-f88d-4127-b328-9b69903624fc: Orders # Orders
    18ab3594-a62d-4903-9c6c-b791d64fd4ad: Pages # Pages
    21dd60d6-92a7-4e82-8884-7dbe57d73c6c: Account # Account
    27dc92a5-4575-4a37-ad4a-09eed2b40038: Page # Page
    31a2d43c-7290-4d37-a001-865d49555f73: Address # Address
    32faa6bc-a330-408a-b37a-4e8bde606b43: Reviews # Reviews
    51e3a5d4-240b-447d-88c5-443e30489a59: 'Equipment Type' # Equipment Type
    63ae8822-3b4e-4a3d-b902-eba33875c230: Footer # Footer
    68e89100-65f8-4cef-9eee-a07652f3e68a: PDFs # PDFs
    77bd0dab-6333-4b99-8a94-7e6042944ba7: Received # Received
    86ec2b26-5d53-4798-8fb0-927890e52039: Body # Body
    97a0491d-814e-4172-811d-51096a86e67d: Plans # Plans
    144eafb4-8a07-46d0-a4b2-e85237275206: 'Plan Features' # Plan Features
    220feec1-8cc9-4f3e-82da-73c748d0ae0b: PDFs # PDFs
    229f9f29-ca35-402b-973b-8fb12d4d68ec: Customers # Customers
    344f5ef7-49f4-463b-854e-14b57001ee32: Color # Color
    449f7b84-6b85-4caa-9b9e-1575953516a8: Settings # Settings
    506e9a86-f8ca-4f35-bffc-21da95813979: 'Article Posts' # Article Posts
    678ed5e4-f5a7-4694-9483-fbc5656b7f95: SEO # SEO
    705abccb-1d21-44fe-a3f7-87530e29cd34: 'Product Images' # Product Images
    708be4d3-74b6-4389-a32f-aebc64f33b0d: Heading # Heading
    994a420b-cb3e-4813-be6a-dd7ac7f55c6b: Images # Images
    1620c507-acc0-4d72-ab32-2228a73a088d: Bikes # Bikes
    2170bde4-2ca6-4d6f-b2d0-7367050a564a: Membership # Membership
    3815aa30-9bf2-4a2b-8d16-00fd08c68e86: 'Aria Label' # Aria Label
    4618ebbc-ed9f-4632-8648-dbbfafc12ce5: Heading # Heading
    4735edf8-ae6c-4f28-a8df-338ca5637aab: Button # Button
    5075e975-0eb8-4e62-9ae7-9d8cd88348eb: Emails # Emails
    5572edd6-3495-4a53-8f09-68bb6c53d79a: 'Main Image' # Main Image
    5712e1f3-7800-493e-b74b-c2887dc25c81: 'Spoke & Chain' # Spoke & Chain
    6443fbe4-a797-4f2a-8b81-c76619128990: 'Button URL' # Button URL
    8680f635-edfc-4169-a039-4c4a489258d7: Homepage # Homepage
    19549c94-cebb-4606-a533-aaef9dc49de7: Geometry # Geometry
    21814db2-4816-41e4-bdc9-7d25e0869666: Register # Register
    56579ab7-dd43-426d-a734-d7fbc26fa861: Search # Search
    60203e95-0439-4fdf-a99f-b85c845abc12: Homepage # Homepage
    73150d2f-c0ce-44c6-a07a-1521dd2e2c5c: Shipping # Shipping
    384841aa-9783-4efd-a81f-0f4aa159ab33: Bikes # Bikes
    520350fa-6eaf-4bc0-9568-687055d5b462: Form # Form
    562224df-c083-4f48-b0b3-7bdcb9bd8df9: Material # Material
    706870b0-b231-4710-947c-e3e6bd5c7062: Articles # Articles
    938640bc-562a-4bde-9ab8-4c0b3489b21f: Login # Login
    03450688-d7c8-4bc8-bd13-fff95a960e2b: Bike # Bike
    45736170-97df-40d3-95b7-41f641c8d3d0: 'Public Schema' # Public Schema
    a004cfa0-a7f8-419b-8343-d6670a0a52e8: Heading # Heading
    a3bf7c5e-7238-4c5d-bb83-0f4080941958: Dummy # Dummy
    a9d8c265-1ab4-4dc0-8408-7889d17f4e02: 'Order Shipped' # Order Shipped
    a42d1365-22cd-445e-9e10-43dc721bddbe: Button # Button
    a853d93f-f289-4671-b5d1-61a8099d5abb: Articles # Articles
    a47082e1-a4c7-48c4-b08e-e84d5dae0956: Search # Search
    aa9bb63f-85d8-4935-8f06-939e8b8707ae: Delivered # Delivered
    aa40a16f-55f6-4e2c-818c-5e1f6a3a5b57: 'Bike Types' # Bike Types
    ab1e76a4-82ae-4059-900e-5f9d8df35d49: Articles # Articles
    acc12fef-5130-43fe-97ca-e77013797195: Shipped # Shipped
    b0c13f72-1314-4872-b963-24bc1c170d1f: Map # Map
    b0e92218-875e-4e1f-8457-ec090e59278a: 'Opening Times' # Opening Times
    b9cb6112-ebae-420b-bae9-a54c387419f6: 'Footer Nav' # Footer Nav
    b29c63ea-aba1-4ef6-80be-a0096df13673: Cart # Cart
    ba795823-7853-4c7d-8337-136027e1e738: Bikes # Bikes
    bd167f4d-e985-4aec-b6e4-9ba85fbe69f9: 'Content Builder' # Content Builder
    be4e2a2f-de59-4443-a08e-476d20bc36d6: Plans # Plans
    c6eb6f01-8c28-440f-afa6-6b7563ae7a47: Success # Success
    c31c5919-08e9-4f36-a47e-1c2c169b993a: 'Error Pages' # Error Pages
    c72e6534-fbe0-487c-8612-387f5ec5f0c5: 'Full Width Image' # Full Width Image
    cb3481b3-e34c-4104-b4da-6f86236f44ca: Product # Product
    d3fad61c-dfb9-4da2-bb75-6d2910c3c4ca: 'Plain Text 1' # Plain Text 1
    d64cd626-dade-430d-98d1-9b9be69592c0: Services # Services
    d5599be5-4ce7-4f5f-997b-843257caca75: Heading # Heading
    d6666f58-4d11-4bd3-b5bd-bc92b52a538c: Products # Products
    d52553ad-dd63-4dfd-8740-d53484afbcb3: Product # Product
    dc8a137a-73b2-4265-8824-3bae6e662462: Confirmed # Confirmed
    dcd08ed8-faa8-45a2-8716-27077ce6410f: Invoice # Invoice
    dcef5c5f-2446-44fa-8898-1bc3daa2d2fd: 'Equipment Types' # Equipment Types
    dd4a6a83-ea8a-4ad5-abca-4a2d8ae87373: Address # Address
    e7ec0fe3-e0bc-474d-837d-3159984e36f3: SEO # SEO
    e9eeb095-1668-49fe-99a2-36721c1bdbec: Icon # Icon
    e43faa4d-d8c4-4527-a298-2d64a1c9061b: Products # Products
    e60fd5c1-9f1b-496d-8369-a9daafcc185d: 'Plain Text 2' # Plain Text 2
    e177ffea-3077-40f7-8dda-265effea6592: Form # Form
    e1227ec6-29cc-4c76-8ef1-a091a264b805: 'Product Categories' # Product Categories
    edcd5813-3fcd-4824-9a2e-e1f6d92c7fdf: Subheading # Subheading
    ee205f0d-9016-48b3-8c84-df68b08003cd: 'Entry Link' # Entry Link
    f2df00c0-373c-4c6a-8b92-af04075dd56c: Contact # Contact
    f3c02b05-5d6b-423e-96b9-0071d0284f5b: Dashboard # Dashboard
    f3de475b-4a85-4e74-b144-4ff3e464f057: 'Bike Type' # Bike Type
    f6e39d3c-bc6d-4fac-b921-c655cde09804: Checkout # Checkout
    fa42e7b9-0e6f-4d2b-8bf7-9fb4e1cc9010: Body # Body
    fcaf6130-3481-4680-bf31-2ee9b178c554: Stars # Stars
    ffe46793-3b3a-449d-a04e-5481d759fb9f: Reviews # Reviews
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '1.2'
  commerce:
    edition: pro
    enabled: true
    schemaVersion: 3.4.11
  default-dashboard:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      excludeAdmin: ''
      logErrors: false
      logInfo: false
      override: ''
      userDashboard: '1'
  freeform:
    edition: pro
    enabled: true
    schemaVersion: 3.3.2
    settings:
      ajaxByDefault: false
      alertNotificationRecipients: null
      autoScrollToErrors: true
      badgeType: all
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      customErrorMessage: null
      customHoneypotName: null
      defaultTemplates: true
      defaultView: dashboard
      digestRecipients: null
      displayFeed: true
      emailTemplateDirectory: null
      emailTemplateStorage: db
      fieldDisplayOrder: name
      fillWithGet: false
      footerScripts: false
      formSubmitDisable: false
      formSubmitExpiration: null
      formTemplateDirectory: null
      formattingTemplate: flexbox.html
      freeformHoneypot: true
      freeformHoneypotEnhancement: false
      hideBannerDemo: false
      hideBannerOldFreeform: false
      minimumSubmitTime: null
      pluginName: null
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaErrorMessage: 'Please verify that you are not a robot.'
      recaptchaKey: null
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaSize: normal
      recaptchaTheme: light
      recaptchaType: v2_checkbox
      removeNewlines: false
      renderFormHtmlInCpViews: true
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      scriptInsertLocation: footer
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      showTutorial: false
      spamFolderEnabled: true
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.10
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      generatorEnabled: true
      headersEnabled: true
      lowercaseCanonicalUrl: '1'
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 'null'
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '-'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  starfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: false
  name: 'Spoke & Chain'
  retryDuration: null
  schemaVersion: 3.7.7
  timeZone: America/Los_Angeles
