defaultPlacement: end
enableVersioning: true
entryTypes:
  - ab1e76a4-82ae-4059-900e-5f9d8df35d49 # Articles
handle: articles
name: Articles
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - 'Listing page'
      -
        - urlFormat
        - articles
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: _views/articles/post
    uriFormat: 'articles/{slug}'
type: channel
