defaultPlacement: end
enableVersioning: true
entryTypes:
  - 1620c507-acc0-4d72-ab32-2228a73a088d # Bikes
handle: bikesLanding
name: Bikes
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: _views/categories/bikes
    uriFormat: bikes
type: single
