defaultPlacement: end
enableVersioning: true
entryTypes:
  - ab006600-8f38-47a9-a12d-6627bcac15d9 # Checkout: Shipping
handle: checkoutShipping
name: 'Checkout: Shipping'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: _views/checkout/shipping
    uriFormat: checkout/shipping
type: single
