defaultPlacement: end
enableVersioning: true
entryTypes:
  - 20eb0536-818f-47ab-b3d8-762b36d90162 # Checkout: Success
handle: checkoutSuccess
name: 'Checkout: Success'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: _views/checkout/success
    uriFormat: checkout/success
type: single
