defaultPlacement: end
enableVersioning: true
entryTypes:
  - d1927da5-c26d-4063-b443-dc05b85a6468 # Checkout: Address
handle: checkoutAddress
name: 'Checkout: Address'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: _views/checkout/address
    uriFormat: checkout/address
type: single
