enableVersioning: true
handle: checkout
name: Checkout
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81:
    enabledByDefault: true
    hasUrls: true
    template: _views/checkout/index
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 2
  uid: de07e5ba-bde1-43ad-a8ce-2a9d553214bf
type: structure
