defaultPlacement: end
enableVersioning: true
entryTypes:
  - 0dbacfe0-78ef-48ff-95a3-b7eb4dc8be86 # Emails
handle: emails
name: Emails
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
