defaultPlacement: end
enableVersioning: true
entryTypes:
  - c31c5919-08e9-4f36-a47e-1c2c169b993a # Error Pages
handle: errorPages
name: 'Error Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
