defaultPlacement: end
enableVersioning: true
entryTypes:
  - 8680f635-edfc-4169-a039-4c4a489258d7 # Homepage
handle: homepage
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: _views/homepage/index
    uriFormat: __home__
type: single
