defaultPlacement: end
enableVersioning: true
entryTypes:
  - 68e89100-65f8-4cef-9eee-a07652f3e68a # PDFs
handle: pdfs
name: PDFs
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
