defaultPlacement: end
enableVersioning: true
entryTypes:
  - ffe46793-3b3a-449d-a04e-5481d759fb9f # Reviews
handle: reviews
name: Reviews
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
