defaultPlacement: end
enableVersioning: true
entryTypes:
  - 56579ab7-dd43-426d-a734-d7fbc26fa861 # Search
handle: search
name: Search
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: _views/search/index
    uriFormat: search
type: single
