defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2af1095c-7195-4f2b-ad59-d4e36ee17dd9 # Services
handle: servicesLanding
name: Services
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: _views/services/index
    uriFormat: services
type: single
