name: Update dependencies & seed db

on:
  workflow_dispatch:
  push:
    branches:
      - feature/dvo-126-auto-updatepr-bot-for-demos
jobs:
  update:
    runs-on: ubuntu-latest
    name: Update dependencies & seed db
    steps:
      - uses: actions/checkout@v2

      - run: make update

      - run: git status

      - name: Copy files to host
        run: |
          docker cp "$(docker-compose ps -q console)":/app/composer.lock ./
          && docker cp "$(docker-compose ps -q console)":/app/seed.sql ./
          && docker cp "$(docker-compose ps -q console)":/app/config/project ./config/project

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: [GHA] Update dependencies & seed db